# Generated by Django 3.2.5 on 2021-07-26 06:26

import all_jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=all_jobs.models.img_uplode),
        ),
    ]
