# Generated by Django 3.2.5 on 2021-07-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_jobs', '0002_auto_20210726_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='all_jobs.jobs'),
            preserve_default=False,
        ),
    ]
