# Generated by Django 3.2.5 on 2021-07-27 09:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.CharField(max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
