# Generated by Django 3.2.5 on 2021-07-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210723_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
