# Generated by Django 3.2.5 on 2021-07-24 03:39

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210723_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.img_uplode),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
