# Generated by Django 3.2.5 on 2021-07-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210725_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
