# Generated by Django 3.2.5 on 2021-07-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_jobs_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
