# Generated by Django 3.2.5 on 2021-07-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_jobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
