# Generated by Django 3.2.5 on 2021-07-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_jobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True),
        ),
    ]
